[package]
name = "caret"
version = "0.1.0"
authors = ["AlephAlpha <alephalpha911@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
muicss-yew = { path = "../.." }
wasm-bindgen = "0.2"
yew = "0.17"
